apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "config.openshift.io/v1",
          "kind": "Network",
          "metadata": {
            "name": "cluster"
          },
          "spec": {
            "clusterNetwork": [
              {
                "cidr": "10.128.0.0/14",
                "hostPrefix": 23
              }
            ],
            "networkType": "None",
            "serviceNetwork": [
              "172.30.0.0/16"
            ]
          }
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "APIServer",
          "metadata": {
            "name": "tigera-secure"
          },
          "spec": {}
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "Compliance",
          "metadata": {
            "name": "tigera-secure"
          }
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "Installation",
          "metadata": {
            "name": "default"
          }
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "IntrusionDetection",
          "metadata": {
            "name": "tigera-secure"
          }
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "LogCollector",
          "metadata": {
            "name": "example-logcollector"
          }
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "LogStorage",
          "metadata": {
            "name": "tigera-secure"
          },
          "spec": {
            "nodes": {
              "count": 1
            }
          }
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "ManagementClusterConnection",
          "metadata": {
            "name": "tigera-secure"
          }
        },
        {
          "apiVersion": "operator.tigera.io/v1",
          "kind": "Manager",
          "metadata": {
            "name": "tigera-secure"
          }
        }
      ]
    capabilities: "Seamless Upgrades"
    categories: Logging & Tracing, Monitoring, Networking, Security
    certified: "true"
    containerImage: quay.io/tigera/operator:v1.3.1
    createdAt: '"2020-03-12T18:35:33.281006644Z"'
    description: An operator which manages the lifecycle of a Calico or Calico Enterprise
      installation on Kubernetes or OpenShift. Its goal is to make installation, upgrades,
      and ongoing lifecycle management of Calico and Calico Enterprise as simple and
      reliable as possible.
    marketplace.openshift.io/action-text: Install-time Instructions
    marketplace.openshift.io/remote-workflow: https://docs.projectcalico.org/getting-started/openshift/installation
    repository: https://github.com/tigera/operator
    support: Tigera
  name: tigera-operator.v1.3.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: APIServer installs the Tigera API server and related resources.
        At most one instance of this resource is supported. It must be named "tigera-secure".
      kind: APIServer
      name: apiservers.operator.tigera.io
      version: v1
      displayName: APIServer
    - description: Compliance installs the components required for Tigera compliance
        reporting. At most one instance of this resource is supported. It must be
        named "tigera-secure".
      kind: Compliance
      name: compliances.operator.tigera.io
      version: v1
      displayName: Compliance
    - description: Installation configures an installation of Calico or Calico Enterprise.
        At most one instance of this resource is supported. It must be named "default".
        The Installation API installs core networking and network policy components,
        and provides general install-time configuration.
      kind: Installation
      name: installations.operator.tigera.io
      version: v1
      displayName: Installation
    - description: IntrusionDetection installs the components required for Tigera
        intrusion detection. At most one instance of this resource is supported. It
        must be named "tigera-secure".
      kind: IntrusionDetection
      name: intrusiondetections.operator.tigera.io
      version: v1
      displayName: IntrusionDetection
    - description: LogCollector installs the components required for Tigera flow and
        DNS log collection. At most one instance of this resource is supported. It
        must be named "tigera-secure". When created, this installs fluentd on all
        nodes configured to collect Tigera log data and export it to Tigera's Elasticsearch
        cluster as well as any additionally configured destinations.
      kind: LogCollector
      name: logcollectors.operator.tigera.io
      version: v1
      displayName: LogCollector
    - description: LogStorage installs the components required for Tigera flow and
        DNS log storage. At most one instance of this resource is supported. It must
        be named "tigera-secure". When created, this installs an Elasticsearch cluster
        for use by Calico Enterprise.
      kind: LogStorage
      name: logstorages.operator.tigera.io
      version: v1
      displayName: LogStorage
    - description: ManagementClusterConnection represents a link between a managed
        cluster and a management cluster. At most one instance of this resource is
        supported. It must be named "tigera-secure".
      kind: ManagementClusterConnection
      name: managementclusterconnections.operator.tigera.io
      version: v1
      displayName: ManagementClusterConnection
    - description: Manager installs the Calico Enterprise manager graphical user interface.
        At most one instance of this resource is supported. It must be named "tigera-secure".
      kind: Manager
      name: managers.operator.tigera.io
      version: v1
      displayName: Manager
    - description: TigeraStatus represents the most recently observed status for Calico
        or a Calico Enterprise functional area.
      kind: TigeraStatus
      name: tigerastatuses.operator.tigera.io
      version: v1
      displayName: TigeraStatus
  description: "An operator which manages the lifecycle of a Calico or Calico Enterprise
    installation on Kubernetes or OpenShift. Its goal is to make installation, upgrades,
    and ongoing lifecycle management of Calico and Calico Enterprise as simple and
    reliable as possible"
  displayName: Tigera Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAADHlJREFUeNrMWAlwVdUZ/u7bX16Wl0BCNpIXtmwsERIh0EqCKKCCcUAQazXAOIJOgVBpZxjEra1Y2oa6jIwzElRURkAQkCUCiQEMJMBEhISQPUL2vLxsj7zl3tv/nLcYkiBi22nPzHn33XPvOec7379f4P+8CXc7YXR0dHa4P9Y2dKGEbl+tqqvbf5v3MjVKITtArzB23pRq7aJ8D71r+a8CpE3TksOEvO1LgW4b8NIxGScrwTY1Dnw33F+J5JEa2B0Simt70W5XbSWAWXcLUHk3LwcZjS+vn6pKMvkooTNImBsrgJjUhU+Yhb9lZ2PxE0/AYDCgpeoSUk1a2JyA5aaIiZE+KGt2hNL8Lzs6Oy3/cQaJuQy6ZFM3nV6uQtbXTlxtAbYvdk1f/rmMuRlL+P/Dhw5hYrATaqWAwlobHKKMBYl6FNbZ0dojsle2ulXD8m8DJGBMdNk+BkPmvIceQu6B3TjzgoCJ/5D5cwaCidKgEYgpCbPGiHTPWJVR/ANQ3upa577ROtSZnUie/RjOFxejrraWgXuMQOb/YhG7weVFR0fPzVq3DtNSU1H17V6+aWW7gEnhGkyN0iI8QIlgXxK5WoHIABEr7gVmmAQsniQQYAHtVqCkQYJORfcPPYYlS5ey5XVlZWWZJPI6EnnJXQP0gJs8ZUrSmrVrMWz4cMiyjHd3fIHOPhVmEiOVbSRG2pSJUKcWYHXICDGISBnpMiAG7EwtOKPzE0j0VyUkTpqC0NBQxMXHI5jWvFpWluFnMPwkSOXtwN0zeXLS6jVroFKpOLhPd34Cp7mOWyYDdd0iot6qR0D0BA62t7sLo4fJOH8deOtqPAo7R+Pz09cREwQ8NVnA0XLg3HeVmDFjBl9zZFQUJkyYgPy8vIyfYlIxxFj2yJEjk5YtWw6nU+S9ubkZZ/OOcHAe3SPvgfzTp7Fw0SLsPfgV1CHj+LOWiIXY9v77yFy+HJ/s2sXHvrwCiLIKIcpOHDt61LtueEQkltF7bE8iJumOAJm1+vj4ZK56/nlotVpIosj7udMFCNaJqGjohVN0GUhEZCS//um113Dj+nX4+/vz+7jRkTh39ize2roV8QkJ8NMKOFAqY+xwNcYMV6Go8Ix3XdanTUtF6vTpTGo5P4fB7PT0WTAaAyHSZE+vKL8KrVoJFTHHOmvDxGbs/2wH3iO2Sr49gR9Ki0nfgF/35PDrxk2bcHTbiyReuFl3MS9aO25Zm/VFJAW9Xp/Eos9AgKr+oSkoaJhp7rx5fFL/ZpPItUT6eu+ZzjH3cuWrbby39krQB4aiXaPDt9UNmIP18HWokGgTcKGLHUjmc+JHqPn8getrNFosXLgIO3d+/DLd7rgdgy/PnTt30OlYDwwM5CA8jeIrGYMdBdU2HKtWoFU7CpJSh3Md4dh20R8rTsRi8W4RSw44UVanxOsPEHOSA3UdZEx2acg9klNSGIumgSwq3OwxBTUlJiZyvVAqFFzHku9NQQKNxcbFcUfLGtukjSICc8xaYxgeWbAA+w8exPwF82Ext+ODnBxkv/02wpJmorxDQmOvjC8vA6tSBYoKdowal4i21laup709PbfoYwqBpPboUCLOSEwcj+CQEESbosmtAPW1tdDpdHyxWbPux4njxwmUGdGBKs7m7KUvIJIOMWrMGAiCgNXkL1ljhmG322GKicHB9evx6oqHsf1h1ybvFQIPL56Dffv2oa+pDEVF57By5SovmMmTp6CgoCBjKBHPjKEFmW+qqarGle+/h5L7P8l7ukWLHkdxgyukUdDA0SNHQI4cWzZvRnFRkXfBrq4uvLRhA+KI9by8PKSYXOMs8wkbn4609HQ6uBYRRjU6GypRUXENotPJe+iIEZwUljUNBJjEHtptNiiVSuoKDGfRQ5IhSRLvI4jdpzNXcL1rY0bRXYOnnnwS96Wl4VRBAdauXo3q6mps2rgRWtrk8OHDOLVrC48sj38s4wfNZGRlreNrmqJNXE3GDhdw/vz5W3QxLCyM4xkoYmMUsSfJLjCiKPH/rLF7j+W1k44lhMho6rSh26GgiNKE/E828+csu2EhjgGyal0L+9E164CEaaEKtJDeeNak+I6CXAkmoxIFV0tp7R+lGjoiFDU1NcZBboYBkCWXhUnu//1dwtTpqThy7Cg23KuGX5ATu0pEHLsm4FIDxUuSg1EvIC4EdC/DKQsYrpcxIVTCOxkKTNCrsWT/d7hpvcnF6+fn54qzCpKWaOVr95DB+Pr64kppKQrPFmJIgJJbpJ7//RlsJWMxl51F7Bg1BJ0SL6YDZW0ynvvNanKUnaituOJKreaMhKQJwOXjO/D3R0iP7QrI3cD8GCWJsxjTp88Y5AcrKyox6Z4kNDU0kseUh3bUnDUuYpF32Sti0pXYWFy8cBHpI4kqDY0LMsukoYiYhqdXrhsyC5mfX0QiL4OvgjZUy3zuH48dQyqlbZTFwEfNfKMLaEhIMNrb2sjAOnliMqSjNpvNnDWDwZeyDTVCw8JdjJI+lpeWYd/evUiOoskiRQalKyF94MEHb5vHsWcsdxTYDnSmiGAJvY2VfM2C06cQHaRCj9UObUAoH2PG09bSiqsk4qEA1nZ0dLgZdLkWRrX3njrLaOKjJSgCHRDULgaZz7tdY8/YIdhhFEYnFJQrDlPasfmNv8BfMsNX5UCtRUYivcf28bi05uYWjmcgwJL6+nqvW2FWzKju72YYYGaVP7d5spsfM08ZySMUkJqvYBzljY3mm7AIQYiPjXPvI/N9W1o5wJKBAL+prKr0uhmmd3C7BY+jVttab9mPgWVO+XatjEQV7j94XE3hztxpxTWLGm9u2cLV6WZfH2ewoqqCs0e1SslAI9nf2taW3dnZxazCzSD4yUS3FdvVw+i30bsR83e7cnNvq4df07NXxw8e77I6cKNXg2m/uh9+pO9nz53Ftp2fQwcn3es4lkE6SIiZzPfv2L4ddTW1FPTNOPNNgVe8XMSyyxF7Wmwwxetze/DFnj2DQLCx0O6zXga5q3FQ1GiWUGs14LnfvQhfqp9XrVqJk6ootM7+Pay6WWgw8wqE5YWmQTUJ1QXNNxpuZEZRGq5QCBg/aSKiKHHwDwhAc2Mjz5q1tibujD2NVW2vvJ+LS9dcGTV7523KpAv3bsXrcwRoST5yH4GzKtFFm+dU6fGHDZtw6NBB5N6womneWthGJ0NpE2Gob4dCPwqCNswEh3ltoJ/WSJjOCQNS/rzoqKi02ZRV/zrNFa9P5btKV+bpq4v24IPHBe4+GIOetvPij+yGU5B4tJ9o2btjBQ12XpZwQkxEU3MTypKXoo+AeZq2tQPB+RcQPzYUNxot6Orpg2Q5BclamT4w5V9WV19vKb92zStakYob1vU6PXoN8RzMX/NlfHhBy/s/z+hoTEH5HngvrlJAbNFAalfz/ubXVMhTTphTLpDFxiKQyglJaxjslgjcR+8+gzc2utNBpd+tkcSji8RiVtGF8zlGEi1bzNM6LBZ093RzcIy9Yiovgw2u87EKjzHFdO58K3kAUQ2ZHHq33cVs1kknbNCjorKSuy+FrZfPeyohBJdae6E0KPHRhtl87J0PvnGHNttggG6QOwjkzNwTJzJnp6VTAWVEA4mlvcOMXqvVKzZRdiLt/nkYNT4Fz8amIOv5ZxEmXMd7nx6CzlYBsaYI+YdyKavucxGi7ENzWytP5zQ3yriI30yL+XFjhxNPv/Ahyiqa3IbVxLDkD1UXswfL7A77juP5J7nO9Fp7+cIsJUsgzx8REQELjEjJWIWp85bCTqVoh1XE1UYB18lQ7HEPojllJT5rGYHg4GCwZJgV6UFBQTxj8al1ubl5uy+7XMkAcBB7yOrN+3/Ox6NXWDEVNy6WZ7u9N610UFdtwtL6pqYmftVoNAgglWCHYDGdjbH/DBwD5DUGeo+8Py6XXkHDjN/iZsJ9mBhs4EbSuLvA+57bQJYxad7x85s7/c6hgt6UPCmJcjl/Kt6dHASLNDaH47Zz9RpXbNRpdVBQ3VJeWYHKmmr+CY4MJbP9yT8bRf9grxVz0fbVQzSfyCdw6XfzfZBluKwqWuOj1xtHm2IQRoxSmXjHuU2UZDS2NKOeRE8t3/1tMJ9VkgQyz/JIllHQhnKAUm8ppO6SEjKQdM/3w7v9BMyAsrr1Gebx/YlNAgx/d4bsaU5Sg87uLorV3aQSDos7fH048Hugu9zNlgJj0pQ9nUzvWNGe1f/j5l1/RO+3uMld3LAezerqfo+Zr2Cb5PcP/HdYy/JLPrL/z9u/BBgAxapz7tnoxv8AAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          - pods
          - podtemplates
          - services
          - endpoints
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - tigera-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - operator.tigera.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - scheduling.k8s.io
          resources:
          - priorityclasses
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - networks/status
          verbs:
          - update
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - networks
          - infrastructures
          verbs:
          - get
          - '*'
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - '*'
        - apiGroups:
          - apiregistration.k8s.io
          resources:
          - apiservices
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - jobs
          - cronjobs
          verbs:
          - '*'
        - apiGroups:
          - projectcalico.org
          resources:
          - globalreporttypes
          - licensekeys
          - globalalerttemplates
          verbs:
          - '*'
        - apiGroups:
          - elasticsearch.k8s.elastic.co
          resources:
          - elasticsearches
          verbs:
          - '*'
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - '*'
        - apiGroups:
          - kibana.k8s.elastic.co
          resources:
          - kibanas
          verbs:
          - '*'
        serviceAccountName: tigera-operator
      deployments:
      - name: tigera-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: tigera-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: tigera-operator
            spec:
              containers:
              - command:
                - operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: tigera-operator
                image: quay.io/tigera/operator:v1.3.1
                imagePullPolicy: Always
                name: tigera-operator
                resources: {}
              hostNetwork: true
              serviceAccountName: tigera-operator
              tolerations:
              - effect: NoSchedule
                operator: Exists
              - effect: NoSchedule
                operator: Exists
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - networking
  - security
  - monitoring
  links:
  - name: Calico Introduction
    url: https://docs.projectcalico.org/introduction/
  - name: Install an OpenShift v4 cluster with Calico
    url: https://docs.projectcalico.org/v3.13/getting-started/openshift/installation
  maintainers:
  - email: laurence@tigera.io
    name: Laurence Man
  maturity: stable
  provider:
    name: Tigera
  replaces: tigera-operator.v0.0.0
  version: 1.3.1
